[package]
name = "rustsrv"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1.0", features = ["http1", "server"] }
tokio = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
bytes = "1.0"
serde_json = "1.0"